### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by priyanperera** [d4software/QueryTree#85] opened 2019-10-20 13:57 UTC
Hi,

I downloaded the project and tried using it. But, just simply cannot login after a successful registration. The only change I did was to use MSSqlServer as the data store and set the connection string property in appsettings.json. The user gets created without any issues but the login does not work. Getting the following error message from the Authorize attribute.

Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.

Any idea why?

**Comment by d4nt** [comment] 2019-10-20 16:15
Hi @priyanperera, I just tried to reproduce this on the latest version of master and it worked ok. Are you using the latest code? Were you able to sign up ok? Before signing out then trying to sign in again?

**Comment by priyanperera** [comment] 2019-10-21 04:54
I cloned the latest code. I was able to register/sign up without issues. After signing up, when the user tries to login, the log result is also successful but the redirect fails on the Authorize attribute.

Like I mentioned, I have only changed the data stored to MSSqlServer and added the connection string a new database.

**Comment by d4nt** [comment] 2019-11-22 13:43
Apologies but I just can't reproduce this, closing.

**Closed by d4nt** 2019-11-22 13:43 UTC
Labels: wontfix
