### ISSUE TITLE
Column Names Not Showing in Summarize Drop Down Menu

### ISSUE THREAD

**Issue by zeehasham** [d4software/QueryTree#46] opened 2018-12-04 19:47 UTC
The drop down to select columns is empty when I use Summarize option. The column are visible in Filter option. I am using MySQL as a backend table.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/6742572/49468631-69345e80-f7d3-11e8-82ca-e08c636340e2.png">

I appreciate if you can help me with this issue.

**Comment by dand4** [comment] 2018-12-05 12:33
@zeehasham the issue is probably that the table you've selected doesn't have any number columns in it. The Summarize tool can only calculate the Total/Min/Max/... of number columns. This is a bug with the UI, the solution should be that we remove the Total/Min/Max... options from the list if there are no columns that they can be used on. The "Number of Rows" and the "Breakdown" options would still work though.

**Comment by d4nt** [comment] 2019-07-01 16:06
This issue is fixed by 14ec0e2

**Closed by d4nt** 2019-07-01 16:06 UTC
Labels: bug
