### ISSUE TITLE
[Feature Request] Set home URL

### ISSUE THREAD

**Issue by sidneydemoraes** [d4software/QueryTree#28] opened 2018-08-31 14:03 UTC
Hello. Would it be possible to add some kind of customization of the home URL likewise Wordpress?
Reason: I am trying to redirect the querytree docker container to `mydomain.com/mydirectory` but all static files point to root (/), which returns 404.

**Comment by ayr-ton** [comment] 2018-08-31 14:04
The planets are aligned. Just opened #29

**Comment by dand4** [comment] 2018-09-19 11:46
Duplicate of #29

**Closed by dand4** 2018-09-19 11:46 UTC
